<a href="https://colab.research.google.com/github/Rhymster16/Global-Job-market-analysis/blob/main/Global_Job_Market_Intelligence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
PROJECT_PATH = "/content/drive/MyDrive/Indian_Job_Market_Intelligence"

In [ ]:
os.listdir(PROJECT_PATH)

['Data Inventory Sheet.xlsx',
 'Coloumn Mapping.xlsx',
 'Skill_Dictionary.xlsx',
 'Industry_Mapping.xlsx',
 'Cleaning_Rules.xlsx',
 'Master_Schema.xlsx',
 'DATA']

In [ ]:
RAW_PATH = f"{PROJECT_PATH}/DATA/RAW"

os.listdir(RAW_PATH)

['DS06 NaukriData_Data Science.csv',
 'DS04 Naukri_Data_Scientist_and_Data_Analytics_Jobs_Data.csv',
 'DS05 NaukriData_data analytics.csv',
 'DS02 linkedin_job_posts_insights.csv',
 'DS03 JobData.csv',
 'DS01 clean_jobs.csv']

In [ ]:
ds01 = pd.read_csv(f"{RAW_PATH}/DS01 clean_jobs.csv")

ds02 = pd.read_csv(f"{RAW_PATH}/DS02 linkedin_job_posts_insights.csv")

ds03 = pd.read_csv(f"{RAW_PATH}/DS03 JobData.csv")

ds04 = pd.read_csv(
    f"{RAW_PATH}/DS04 Naukri_Data_Scientist_and_Data_Analytics_Jobs_Data.csv"
)

ds05 = pd.read_csv(
    f"{RAW_PATH}/DS05 NaukriData_data analytics.csv"
)

ds06 = pd.read_csv(
    f"{RAW_PATH}/DS06 NaukriData_Data Science.csv"
)

In [ ]:
datasets = {
    "DS01_LinkedIn_Jobs": ds01,
    "DS02_LinkedIn_Insights": ds02,
    "DS03_Internships": ds03,
    "DS04_Naukri_Mixed": ds04,
    "DS05_Naukri_Analytics": ds05,
    "DS06_Naukri_DataScience": ds06
}

for name, df in datasets.items():
    print(f"{name}: {df.shape}")

DS01_LinkedIn_Jobs: (1048, 10)
DS02_LinkedIn_Insights: (31597, 9)
DS03_Internships: (431, 6)
DS04_Naukri_Mixed: (19649, 6)
DS05_Naukri_Analytics: (20064, 8)
DS06_Naukri_DataScience: (47191, 8)

In [ ]:
for name, df in datasets.items():
    print("\n" + "="*50)
    print(name)
    print("="*50)
    print(df.columns.tolist())

==================================================
DS01_LinkedIn_Jobs
==================================================
['id', 'title', 'company', 'location', 'link', 'source', 'date_posted', 'work_type', 'employment_type', 'description']

==================================================
DS02_LinkedIn_Insights
==================================================
['job_title', 'company_name', 'location', 'hiring_status', 'date', 'seniority_level', 'job_function', 'employment_type', 'industry']

==================================================
DS03_Internships
==================================================
['Company_Name', 'JobTitles', 'Skills', 'Description', 'Stipend', 'Links']

==================================================
DS04_Naukri_Mixed
==================================================
['Job Titles', 'Company Names', 'Experience Required', 'Package', 'Locations', 'Skills']

==================================================
DS05_Naukri_Analytics
==================================================
['Job_Titles', 'Company_Names', 'Experience_Required', 'Package_Details', 'Locations', 'Skills', 'Post_Url', 'Post_Time']

==================================================
DS06_Naukri_DataScience
==================================================
['Job_Titles', 'Company_Names', 'Experience_Required', 'Package_Details', 'Locations', 'Skills', 'Post_Url', 'Post_Time']

In [ ]:
audit = []

for name, df in datasets.items():
    audit.append([
        name,
        df.shape[0],
        df.shape[1]
    ])

audit_df = pd.DataFrame(
    audit,
    columns=[
        "Dataset",
        "Rows",
        "Columns"
    ]
)

audit_df

                   Dataset   Rows  Columns
0       DS01_LinkedIn_Jobs   1048       10
1   DS02_LinkedIn_Insights  31597        9
2         DS03_Internships    431        6
3        DS04_Naukri_Mixed  19649        6
4    DS05_Naukri_Analytics  20064        8
5  DS06_Naukri_DataScience  47191        8

In [ ]:
import os

reports_path = f"{PROJECT_PATH}/Reports"
os.makedirs(reports_path, exist_ok=True)

audit_df.to_csv(
    f"{reports_path}/Data_Audit_Report.csv",
    index=False
)

In [ ]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.columns.tolist())

DS01_LinkedIn_Jobs
['id', 'title', 'company', 'location', 'link', 'source', 'date_posted', 'work_type', 'employment_type', 'description']

DS02_LinkedIn_Insights
['job_title', 'company_name', 'location', 'hiring_status', 'date', 'seniority_level', 'job_function', 'employment_type', 'industry']

DS03_Internships
['Company_Name', 'JobTitles', 'Skills', 'Description', 'Stipend', 'Links']

DS04_Naukri_Mixed
['Job Titles', 'Company Names', 'Experience Required', 'Package', 'Locations', 'Skills']

DS05_Naukri_Analytics
['Job_Titles', 'Company_Names', 'Experience_Required', 'Package_Details', 'Locations', 'Skills', 'Post_Url', 'Post_Time']

DS06_Naukri_DataScience
['Job_Titles', 'Company_Names', 'Experience_Required', 'Package_Details', 'Locations', 'Skills', 'Post_Url', 'Post_Time']

In [ ]:
def clean_column_names(df):

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("-", "_")
        .str.replace("/", "_")
    )

    return df

In [ ]:
ds01 = clean_column_names(ds01)
ds02 = clean_column_names(ds02)
ds03 = clean_column_names(ds03)
ds04 = clean_column_names(ds04)
ds05 = clean_column_names(ds05)
ds06 = clean_column_names(ds06)

In [ ]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.columns.tolist())

DS01_LinkedIn_Jobs
['id', 'title', 'company', 'location', 'link', 'source', 'date_posted', 'work_type', 'employment_type', 'description']

DS02_LinkedIn_Insights
['job_title', 'company_name', 'location', 'hiring_status', 'date', 'seniority_level', 'job_function', 'employment_type', 'industry']

DS03_Internships
['company_name', 'jobtitles', 'skills', 'description', 'stipend', 'links']

DS04_Naukri_Mixed
['job_titles', 'company_names', 'experience_required', 'package', 'locations', 'skills']

DS05_Naukri_Analytics
['job_titles', 'company_names', 'experience_required', 'package_details', 'locations', 'skills', 'post_url', 'post_time']

DS06_Naukri_DataScience
['job_titles', 'company_names', 'experience_required', 'package_details', 'locations', 'skills', 'post_url', 'post_time']

In [ ]:
# DS01 LinkedIn Jobs
ds01.rename(columns={
    'title':'job_title',
    'company':'company_name',
    'link':'job_url',
    'date_posted':'posted_date',
    'work_type':'work_mode'
}, inplace=True)

# DS02 LinkedIn Insights
ds02.rename(columns={
    'date':'posted_date',
    'job_function':'description'
}, inplace=True)

# DS03 Internships
ds03.rename(columns={
    'jobtitles':'job_title',
    'stipend':'salary',
    'links':'job_url'
}, inplace=True)

# DS04 Naukri Mixed
ds04.rename(columns={
    'job_titles':'job_title',
    'company_names':'company_name',
    'experience_required':'experience',
    'package':'salary',
    'locations':'location'
}, inplace=True)

# DS05 Naukri Analytics
ds05.rename(columns={
    'job_titles':'job_title',
    'company_names':'company_name',
    'experience_required':'experience',
    'package_details':'salary',
    'locations':'location',
    'post_url':'job_url',
    'post_time':'posted_date'
}, inplace=True)

# DS06 Naukri Data Science
ds06.rename(columns={
    'job_titles':'job_title',
    'company_names':'company_name',
    'experience_required':'experience',
    'package_details':'salary',
    'locations':'location',
    'post_url':'job_url',
    'post_time':'posted_date'
}, inplace=True)

In [ ]:
for i, df in enumerate(
    [ds01, ds02, ds03, ds04, ds05, ds06],
    start=1
):
    print(f"\nDataset {i}")
    print(df.columns.tolist())

Dataset 1
['id', 'job_title', 'company_name', 'location', 'job_url', 'source', 'posted_date', 'work_mode', 'employment_type', 'description']

Dataset 2
['job_title', 'company_name', 'location', 'hiring_status', 'posted_date', 'seniority_level', 'description', 'employment_type', 'industry']

Dataset 3
['company_name', 'job_title', 'skills', 'description', 'salary', 'job_url']

Dataset 4
['job_title', 'company_name', 'experience', 'salary', 'location', 'skills']

Dataset 5
['job_title', 'company_name', 'experience', 'salary', 'location', 'skills', 'job_url', 'posted_date']

Dataset 6
['job_title', 'company_name', 'experience', 'salary', 'location', 'skills', 'job_url', 'posted_date']

In [ ]:
required_columns = [
    'job_title',
    'company_name',
    'location',
    'skills',
    'experience',
    'salary',
    'description',
    'posted_date',
    'job_url',
    'source',
    'employment_type'
]

for df in [ds01, ds02, ds03, ds04, ds05, ds06]:

    for col in required_columns:

        if col not in df.columns:
            df[col] = np.nan

In [ ]:
ds01['source'] = 'LinkedIn Jobs'
ds02['source'] = 'LinkedIn Insights'
ds03['source'] = 'Internships'
ds04['source'] = 'Naukri Mixed'
ds05['source'] = 'Naukri Analytics'
ds06['source'] = 'Naukri Data Science'

In [ ]:
master_columns = [
    'job_title',
    'company_name',
    'location',
    'skills',
    'experience',
    'salary',
    'description',
    'posted_date',
    'job_url',
    'source',
    'employment_type'
]

In [ ]:
ds01 = ds01[master_columns]
ds02 = ds02[master_columns]
ds03 = ds03[master_columns]
ds04 = ds04[master_columns]
ds05 = ds05[master_columns]
ds06 = ds06[master_columns]

In [ ]:
print(ds01.head())

         job_title company_name           location  skills  experience  \
0     Data Analyst         Meta       New York, NY     NaN         NaN
1     Data Analyst         Meta  San Francisco, CA     NaN         NaN
2     Data Analyst         Meta    Los Angeles, CA     NaN         NaN
3     Data Analyst         Meta     Washington, DC     NaN         NaN
4  Data Analyst II    Pinterest        Chicago, IL     NaN         NaN

   salary                                        description posted_date  \
0     NaN  The Social Measurement team is a growing team ...   4/14/2025
1     NaN  The Social Measurement team is a growing team ...   4/14/2025
2     NaN  The Social Measurement team is a growing team ...   4/14/2025
3     NaN  The Social Measurement team is a growing team ...   4/14/2025
4     NaN  About Pinterest\n\nMillions of people around t...   4/16/2025

                                             job_url         source  \
0  https://www.linkedin.com/jobs/view/data-analys...  LinkedIn Jobs
1  https://www.linkedin.com/jobs/view/data-analys...  LinkedIn Jobs
2  https://www.linkedin.com/jobs/view/data-analys...  LinkedIn Jobs
3  https://www.linkedin.com/jobs/view/data-analys...  LinkedIn Jobs
4  https://www.linkedin.com/jobs/view/data-analys...  LinkedIn Jobs

   employment_type
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN

In [ ]:
print(ds02.head())

                                           job_title  \
0     Store Business Manager - DAVID JONES CHERMSIDE
1                                          Full-time
2                   Senior Machine Learning Engineer
3                              Senior Data Scientist
4  \n            \n        Solution Architect\n  ...

                               company_name  \
0                                 M.J. Bale
1                                  Gatesman
2                           Redwolf + Rosch
3                                      Bupa
4  \n            Xybion Digital\n

                                            location  skills  experience  \
0                    Brisbane, Queensland, Australia     NaN         NaN
1                                        Chicago, IL     NaN         NaN
2               Adelaide, South Australia, Australia     NaN         NaN
3                     Melbourne, Victoria, Australia     NaN         NaN
4  \n            Chennai, Tamil Nadu, India\n    ...     NaN         NaN

   salary                                        description  \
0     NaN                     Sales and Business Development
1     NaN                                                NaN
2     NaN             Engineering and Information Technology
3     NaN             Engineering and Information Technology
4     NaN  \n            Engineering and Information Tech...

           posted_date  job_url             source  \
0  2023-04-13 00:00:00      NaN  LinkedIn Insights
1  2023-03-31 00:00:00      NaN  LinkedIn Insights
2  2023-04-25 00:00:00      NaN  LinkedIn Insights
3  2023-04-29 00:00:00      NaN  LinkedIn Insights
4  2023-01-26 00:00:00      NaN  LinkedIn Insights

                   employment_type
0                        Full-time
1                              NaN
2                        Part-time
3                        Full-time
4  \n          Full-time\n

In [ ]:
print(ds03.head())

                                    job_title                  company_name  \
0                WordPress Development Intern                  Bauer Bodoni
1                WordPress Development Intern                  Bauer Bodoni
2               ERPNext And HRMS Admin Intern  ESSI Integrated Technologies
3                    Website Operation Intern               Growify Digital
4  Influencer Marketing Data Analytics Intern                    Confluencr

   location                                             skills  experience  \
0       NaN                                          WordPress         NaN
1       NaN                          MS-PowerPoint , WordPress         NaN
2       NaN  Accounting , Enterprise Resource Planning(ERP)...         NaN
3       NaN                             JavaScript , WordPress         NaN
4       NaN  Digital Advertising , English Proficiency (Spo...         NaN

                   salary                                        description  \
0  ₹ 15,000-20,000 /month  Are you a WordPress whiz looking to gain hands...
1  ₹ 15,000-20,000 /month  As a WordPress Development intern at Bauer Bod...
2         ₹ 10,000 /month  Selected intern's day-to-day responsibilities ...
3  ₹ 10,000-15,000 /month  Selected intern's day-to-day responsibilities ...
4         ₹ 20,000 /month  Selected intern's day-to-day responsibilities ...

   posted_date                                            job_url  \
0          NaN  https://internshala.com/internship/detail/word...
1          NaN  https://internshala.com/internship/detail/word...
2          NaN  https://internshala.com/internship/detail/erpn...
3          NaN  https://internshala.com/internship/detail/webs...
4          NaN  https://internshala.com/internship/detail/infl...

        source  employment_type
0  Internships              NaN
1  Internships              NaN
2  Internships              NaN
3  Internships              NaN
4  Internships              NaN

In [ ]:
print(ds04.head())

                                           job_title  \
0  Manager - Digital Product Analytics [Data Scie...
1                        Data Science Domain Manager
2  GN - Strategy - MC - T&O - NLP Data Science - ...
3                               Data Science Manager
4                               Data Science Manager

                company_name  \
0                       Resy
1                   Coursera
2                  Accenture
3  Foreign IT Consulting MNC
4  Foreign IT Consulting MNC

                                            location  \
0                                   Gurgaon/Gurugram
1  Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...
2  Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/...
3                                   Gurgaon/Gurugram
4                                              Noida

                                              skills experience  \
0  Product managementCareer developmentOperations...    4-8 Yrs
1  Computer scienceContent strategyData analysisU...   7-11 Yrs
2  Change managementSASCodingData miningPythonRst...    1-3 Yrs
3  Operations researchSASFinanceProject managemen...    2-6 Yrs
4  Data analysisEDCRisk assessmentrisk modelingMa...    3-6 Yrs

          salary  description  posted_date  job_url        source  \
0  Not disclosed          NaN          NaN      NaN  Naukri Mixed
1  Not disclosed          NaN          NaN      NaN  Naukri Mixed
2  Not disclosed          NaN          NaN      NaN  Naukri Mixed
3  Not disclosed          NaN          NaN      NaN  Naukri Mixed
4  Not disclosed          NaN          NaN      NaN  Naukri Mixed

   employment_type
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN

In [ ]:
print(ds05.head())

                                           job_title  \
0                     Lead Analyst, Data & Analytics
1  Director Data Analytics (Immediate Joiner pref...
2                                Data Analytics Lead
3                             Data Analytics Analyst
4                             Data Analytics Analyst

                company_name  \
0                        ANZ
1        Techneplus Software
2                    Gartner
3  Leading Indian IT Company
4         Foreign MNC in BPO

                                            location  \
0                                Bangalore/Bengaluru
1  Noida, Uttar Pradesh, Bangalore/ Bengaluru, Ka...
2                                   Gurgaon/Gurugram
3                 Noida, Mumbai, Bangalore/Bengaluru
4                                             Jaipur

                                              skills experience  \
0  data cleansingData analysisAutomationData mana...    4-6 Yrs
1  Data ScienceData VisualizationData ModelingDat...  10-15 Yrs
2  Process designChange managementProject managem...    5-8 Yrs
3  Data AnalysisRSASPower BIData VisualizationTab...    4-7 Yrs
4  Data AnalyticsData EngineeringScalaHadoopOLAPS...    7-9 Yrs

          salary  description posted_date  \
0  Not disclosed          NaN  3 Days Ago
1  Not disclosed          NaN   1 Day Ago
2  Not disclosed          NaN   1 Day Ago
3  Not disclosed          NaN  2 Days Ago
4  Not disclosed          NaN   1 Day Ago

                                             job_url            source  \
0  https://www.naukri.com/job-listings-lead-analy...  Naukri Analytics
1  https://www.naukri.com/job-listings-director-d...  Naukri Analytics
2  https://www.naukri.com/job-listings-data-analy...  Naukri Analytics
3                                                NaN  Naukri Analytics
4                                                NaN  Naukri Analytics

   employment_type
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN

In [ ]:
print(ds06.head())

                                           job_title  \
0                      Senior Manager - Data Science
1      Advance Analytical and Data Sciences -Manager
2  Manager - Digital Product Analytics [Data Scie...
3                               Data Science Manager
4                               Data Science Manager

                        company_name  \
0                   AMERICAN EXPRESS
1                  G R Infraprojects
2                               Resy
3          Foreign IT Consulting MNC
4  Fortune India 500 Company in FMCG

                                            location  \
0                                   Gurgaon/Gurugram
1                         Gurgaon/ Gurugram, Haryana
2                                   Gurgaon/Gurugram
3  Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/...
4                                Bangalore/Bengaluru

                                              skills experience  \
0  Text miningCareer developmentdata scienceFinan...    4-8 Yrs
1  Advanced Statistical AnalysisData Governance a...   6-10 Yrs
2  Product managementCareer developmentOperations...    4-8 Yrs
3  Change managementSASCodingData miningPythonRst...    1-3 Yrs
4  Data analysisdata scienceAnalyticalPredictive ...    4-9 Yrs

          salary  description  posted_date  \
0  Not disclosed          NaN    1 Day Ago
1  Not disclosed          NaN   7 Days Ago
2  Not disclosed          NaN   4 Days Ago
3  Not disclosed          NaN  10 Days Ago
4  Not disclosed          NaN    1 Day Ago

                                             job_url               source  \
0  https://www.naukri.com/job-listings-senior-man...  Naukri Data Science
1  https://www.naukri.com/job-listings-advance-an...  Naukri Data Science
2  https://www.naukri.com/job-listings-manager-di...  Naukri Data Science
3                                                NaN  Naukri Data Science
4                                                NaN  Naukri Data Science

   employment_type
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN

In [ ]:
CLEANED_PATH = f"{PROJECT_PATH}/DATA/Cleaned"

In [ ]:
import os

print(os.listdir(f"{PROJECT_PATH}/DATA"))

['RAW']

In [ ]:
import os

CLEANED_PATH = f"{PROJECT_PATH}/DATA/Cleaned"

os.makedirs(CLEANED_PATH, exist_ok=True)

print("Folder Created Successfully")

Folder Created Successfully

In [ ]:
import os
os.makedirs(CLEANED_PATH, exist_ok=True)
ds01.to_csv(f"{CLEANED_PATH}/ds01_clean.csv", index=False)
ds02.to_csv(f"{CLEANED_PATH}/ds02_clean.csv", index=False)
ds03.to_csv(f"{CLEANED_PATH}/ds03_clean.csv", index=False)
ds04.to_csv(f"{CLEANED_PATH}/ds04_clean.csv", index=False)
ds05.to_csv(f"{CLEANED_PATH}/ds05_clean.csv", index=False)
ds06.to_csv(f"{CLEANED_PATH}/ds06_clean.csv", index=False)

In [ ]:
os.listdir(CLEANED_PATH)

['ds01_clean.csv',
 'ds02_clean.csv',
 'ds03_clean.csv',
 'ds04_clean.csv',
 'ds05_clean.csv',
 'ds06_clean.csv']

In [ ]:
ds01 = pd.read_csv(f"{CLEANED_PATH}/ds01_clean.csv")
ds02 = pd.read_csv(f"{CLEANED_PATH}/ds02_clean.csv")
ds03 = pd.read_csv(f"{CLEANED_PATH}/ds03_clean.csv")
ds04 = pd.read_csv(f"{CLEANED_PATH}/ds04_clean.csv")
ds05 = pd.read_csv(f"{CLEANED_PATH}/ds05_clean.csv")
ds06 = pd.read_csv(f"{CLEANED_PATH}/ds06_clean.csv")

In [ ]:
datasets = {
    "DS01": ds01,
    "DS02": ds02,
    "DS03": ds03,
    "DS04": ds04,
    "DS05": ds05,
    "DS06": ds06
}

In [ ]:
for name, df in datasets.items():

    print("\n" + "="*50)
    print(name)
    print("="*50)

    print(df.isnull().sum())

==================================================
DS01
==================================================
job_title             0
company_name          2
location             15
skills             1048
experience         1048
salary             1048
description           4
posted_date          23
job_url               0
source                0
employment_type    1048
dtype: int64

==================================================
DS02
==================================================
job_title             26
company_name         940
location               9
skills             31597
experience         31597
salary             31597
description         1590
posted_date            0
job_url            31597
source                 0
employment_type     1591
dtype: int64

==================================================
DS03
==================================================
job_title            0
company_name         0
location           431
skills               0
experience         431
salary               0
description          0
posted_date        431
job_url              0
source               0
employment_type    431
dtype: int64

==================================================
DS04
==================================================
job_title            127
company_name         127
location              60
skills               183
experience           414
salary               127
description        19649
posted_date        19649
job_url            19649
source                 0
employment_type    19649
dtype: int64

==================================================
DS05
==================================================
job_title             23
company_name           3
location              29
skills               283
experience           296
salary                18
description        20064
posted_date            5
job_url                5
source                 0
employment_type    20064
dtype: int64

==================================================
DS06
==================================================
job_title          13558
company_name       11368
location            8027
skills              9162
experience         11203
salary              8559
description        47191
posted_date         7310
job_url             7350
source                 0
employment_type    47191
dtype: int64

In [ ]:
for name, df in datasets.items():

    print("\n" + "="*50)
    print(name)
    print("="*50)

    missing_percent = (
        df.isnull().mean()*100
    ).round(2)

    print(missing_percent)

==================================================
DS01
==================================================
job_title            0.00
company_name         0.19
location             1.43
skills             100.00
experience         100.00
salary             100.00
description          0.38
posted_date          2.19
job_url              0.00
source               0.00
employment_type    100.00
dtype: float64

==================================================
DS02
==================================================
job_title            0.08
company_name         2.97
location             0.03
skills             100.00
experience         100.00
salary             100.00
description          5.03
posted_date          0.00
job_url            100.00
source               0.00
employment_type      5.04
dtype: float64

==================================================
DS03
==================================================
job_title            0.0
company_name         0.0
location           100.0
skills               0.0
experience         100.0
salary               0.0
description          0.0
posted_date        100.0
job_url              0.0
source               0.0
employment_type    100.0
dtype: float64

==================================================
DS04
==================================================
job_title            0.65
company_name         0.65
location             0.31
skills               0.93
experience           2.11
salary               0.65
description        100.00
posted_date        100.00
job_url            100.00
source               0.00
employment_type    100.00
dtype: float64

==================================================
DS05
==================================================
job_title            0.11
company_name         0.01
location             0.14
skills               1.41
experience           1.48
salary               0.09
description        100.00
posted_date          0.02
job_url              0.02
source               0.00
employment_type    100.00
dtype: float64

==================================================
DS06
==================================================
job_title           28.73
company_name        24.09
location            17.01
skills              19.41
experience          23.74
salary              18.14
description        100.00
posted_date         15.49
job_url             15.58
source               0.00
employment_type    100.00
dtype: float64

In [ ]:
report = []

for name, df in datasets.items():

    for col in df.columns:

        report.append([
            name,
            col,
            df[col].isnull().sum(),
            round(df[col].isnull().mean()*100,2)
        ])

missing_report = pd.DataFrame(
    report,
    columns=[
        "Dataset",
        "Column",
        "Missing_Count",
        "Missing_Percentage"
    ]
)

In [ ]:
REPORT_PATH = f"{PROJECT_PATH}/Reports"

import os
os.makedirs(REPORT_PATH, exist_ok=True)

missing_report.to_csv(
    f"{REPORT_PATH}/Missing_Value_Report.csv",
    index=False
)

In [ ]:
for name, df in datasets.items():

    duplicates = df.duplicated().sum()

    print(f"{name}: {duplicates}")

DS01: 0
DS02: 14589
DS03: 0
DS04: 3
DS05: 34
DS06: 24399

In [ ]:
duplicate_report = []

for name, df in datasets.items():

    duplicate_report.append([
        name,
        len(df),
        df.duplicated().sum()
    ])

duplicate_report = pd.DataFrame(
    duplicate_report,
    columns=[
        "Dataset",
        "Total_Rows",
        "Duplicate_Rows"
    ]
)

duplicate_report

  Dataset  Total_Rows  Duplicate_Rows
0    DS01        1048               0
1    DS02       31597           14589
2    DS03         431               0
3    DS04       19649               3
4    DS05       20064              34
5    DS06       47191           24399

In [ ]:
duplicate_report.to_csv(
    f"{REPORT_PATH}/Duplicate_Report.csv",
    index=False
)

In [ ]:
for name, df in datasets.items():

    print(
        name,
        df['job_title'].nunique()
    )

DS01 523
DS02 6112
DS03 222
DS04 8042
DS05 12030
DS06 3736

In [ ]:
for name, df in datasets.items():

    print(
        name,
        df['company_name'].nunique()
    )

DS01 632
DS02 7201
DS03 301
DS04 5388
DS05 7297
DS06 3211

In [ ]:
summary = []

for name, df in datasets.items():

    summary.append([
        name,
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ])

quality_summary = pd.DataFrame(
    summary,
    columns=[
        "Dataset",
        "Rows",
        "Columns",
        "Missing_Values",
        "Duplicates"
    ]
)

quality_summary

  Dataset   Rows  Columns  Missing_Values  Duplicates
0    DS01   1048       11            4236           0
1    DS02  31597       11          130544       14589
2    DS03    431       11            1724           0
3    DS04  19649       11           79634           3
4    DS05  20064       11           40790          34
5    DS06  47191       11          170919       24399

In [ ]:
quality_summary.to_csv(
    f"{REPORT_PATH}/Data_Quality_Summary.csv",
    index=False
)

In [ ]:
master_jobs = pd.concat(
    [ds01, ds02, ds03, ds04, ds05, ds06],
    ignore_index=True
)

print(master_jobs.shape)

(119980, 11)

In [ ]:
master_jobs_backup = master_jobs.copy()

In [ ]:
master_jobs.isnull().sum()

job_title          13734
company_name       12440
location            8571
skills             42273
experience         44989
salary             41349
description        88498
posted_date        27418
job_url            58601
source                 0
employment_type    89974
dtype: int64

In [ ]:
(master_jobs.isnull().mean()*100).round(2)

job_title          11.45
company_name       10.37
location            7.14
skills             35.23
experience         37.50
salary             34.46
description        73.76
posted_date        22.85
job_url            48.84
source              0.00
employment_type    74.99
dtype: float64

In [ ]:
master_jobs = master_jobs[
    master_jobs['job_title'].notna()
]

In [ ]:
master_jobs = master_jobs[
    master_jobs['job_title'].str.strip() != ""
]

In [ ]:
master_jobs['company_name'] = (
    master_jobs['company_name']
    .fillna('Unknown Company')
)

In [ ]:
master_jobs['skills'] = (
    master_jobs['skills']
    .fillna('Not Specified')
)

In [ ]:
master_jobs['salary'] = (
    master_jobs['salary']
    .fillna('Unknown')
)

In [ ]:
master_jobs['location'] = (
    master_jobs['location']
    .fillna('Unknown')
)

In [ ]:
city_map = {
    'Bangalore':'Bengaluru',
    'bangalore':'Bengaluru',
    'BANGALORE':'Bengaluru',
    'Gurgaon':'Gurugram',
    'gurgaon':'Gurugram',
    'Bombay':'Mumbai'
}

In [ ]:
master_jobs['location'] = (
    master_jobs['location']
    .replace(city_map)
)

In [ ]:
master_jobs['skills'] = (
    master_jobs['skills']
    .astype(str)
    .str.lower()
)

In [ ]:
master_jobs['skills'] = (
    master_jobs['skills']
    .str.strip()
)

In [ ]:
master_jobs.drop_duplicates(
    inplace=True
)

In [ ]:
master_jobs.drop_duplicates(
    subset=[
        'job_title',
        'company_name',
        'location'
    ],
    inplace=True
)

In [ ]:
master_jobs['job_title'] = (
    master_jobs['job_title']
    .astype(str)
    .str.strip()
    .str.title()
)

In [ ]:
master_jobs['company_name'] = (
    master_jobs['company_name']
    .astype(str)
    .str.strip()
)

In [ ]:
cleaning_summary = pd.DataFrame({
    'Metric':[
        'Rows After Cleaning',
        'Columns'
    ],
    'Value':[
        len(master_jobs),
        len(master_jobs.columns)
    ]
})

cleaning_summary

                Metric  Value
0  Rows After Cleaning  56628
1              Columns     11

In [ ]:
import os

PROCESSED_PATH = f"{PROJECT_PATH}/Data/Processed"

os.makedirs(
    PROCESSED_PATH,
    exist_ok=True
)

In [ ]:
master_jobs.to_csv(
    f"{PROCESSED_PATH}/master_jobs_clean.csv",
    index=False
)

In [ ]:
cleaning_summary.to_csv(
    f"{REPORT_PATH}/Cleaning_Summary.csv",
    index=False
)

In [ ]:
PROCESSED_PATH = f"{PROJECT_PATH}/DATA/Processed"
master_jobs = pd.read_csv(
    f"{PROCESSED_PATH}/master_jobs_clean.csv"
)

master_jobs.shape

(56628, 11)

In [ ]:
def classify_experience(exp):

    exp = str(exp)

    if '0' in exp or 'fresher' in exp.lower():
        return 'Fresher'

    elif '1' in exp or '2' in exp:
        return 'Junior'

    elif '3' in exp or '4' in exp or '5' in exp:
        return 'Mid'

    else:
        return 'Senior'

In [ ]:
master_jobs['experience_level'] = (
    master_jobs['experience']
    .apply(classify_experience)
)

In [ ]:
master_jobs['experience_level'].value_counts()

experience_level
Junior     17514
Senior     15239
Mid        15221
Fresher     8654
Name: count, dtype: int64

In [ ]:
master_jobs['skill_count'] = (
    master_jobs['skills']
    .astype(str)
    .str.split(',')
    .str.len()
)

In [ ]:
master_jobs['skill_count'].describe()

count    56628.000000
mean         1.029862
std          0.418515
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         17.000000
Name: skill_count, dtype: float64

In [ ]:
ai_keywords = [
    'ai',
    'artificial intelligence',
    'chatgpt',
    'openai',
    'llm',
    'langchain',
    'genai',
    'prompt engineering',
    'machine learning',
    'deep learning'
]

In [ ]:
def ai_score(text):

    text = str(text).lower()

    score = 0

    for word in ai_keywords:

        if word in text:
            score += 1

    return score

In [ ]:
master_jobs['ai_adoption_score'] = (
    master_jobs['description']
    .apply(ai_score)
)

In [ ]:
master_jobs['ai_flag'] = (
    master_jobs['ai_adoption_score']
    > 0
).astype(int)

In [ ]:
master_jobs['ai_flag'].value_counts()

ai_flag
0    55321
1     1307
Name: count, dtype: int64

In [ ]:
tier1 = [
    'Bengaluru',
    'Mumbai',
    'Delhi',
    'Pune',
    'Hyderabad',
    'Chennai',
    'Noida',
    'Gurugram'
]

In [ ]:
def city_tier(city):

    city = str(city)

    if city in tier1:
        return 'Tier 1'

    elif city == 'Unknown':
        return 'Unknown'

    else:
        return 'Tier 2/3'

In [ ]:
master_jobs['city_tier'] = (
    master_jobs['location']
    .apply(city_tier)
)

In [ ]:
master_jobs['posted_date'] = pd.to_datetime(
    master_jobs['posted_date'],
    errors='coerce'
)

In [ ]:
master_jobs['posting_month'] = (
    master_jobs['posted_date']
    .dt.month_name()
)

In [ ]:
master_jobs['posting_year'] = (
    master_jobs['posted_date']
    .dt.year
)

In [ ]:
import re

def extract_salary_min(text):

    try:
        nums = re.findall(r'\d+', str(text))

        if len(nums) > 0:
            return float(nums[0])

        return None

    except:
        return None

In [ ]:
def extract_salary_max(text):

    try:
        nums = re.findall(r'\d+', str(text))

        if len(nums) > 1:
            return float(nums[1])

        elif len(nums) == 1:
            return float(nums[0])

        return None

    except:
        return None

In [ ]:
master_jobs['salary_min'] = (
    master_jobs['salary']
    .apply(extract_salary_min)
)

master_jobs['salary_max'] = (
    master_jobs['salary']
    .apply(extract_salary_max)
)

In [ ]:
master_jobs['salary_midpoint'] = (
    master_jobs['salary_min']
    + master_jobs['salary_max']
) / 2

In [ ]:
master_jobs['hiring_complexity_score'] = (
    master_jobs['skill_count']
    +
    master_jobs['ai_adoption_score']
)

In [ ]:
master_jobs[[
    'experience_level',
    'skill_count',
    'ai_adoption_score',
    'ai_flag',
    'city_tier',
    'salary_min',
    'salary_max',
    'salary_midpoint',
    'hiring_complexity_score'
]].head()

,experience_level,skill_count,ai_adoption_score,ai_flag,city_tier,salary_min,salary_max,salary_midpoint,hiring_complexity_score
0,Senior,1,3,1,Tier 2/3,NaN,NaN,NaN,4
1,Senior,1,3,1,Tier 2/3,NaN,NaN,NaN,4
2,Senior,1,3,1,Tier 2/3,NaN,NaN,NaN,4
3,Senior,1,3,1,Tier 2/3,NaN,NaN,NaN,4
4,Senior,1,1,1,Tier 2/3,NaN,NaN,NaN,2

In [ ]:
master_jobs.to_csv(
    f"{PROCESSED_PATH}/master_jobs_featured.csv",
    index=False
)

In [ ]:
import pandas as pd

df = pd.read_csv(f"{PROCESSED_PATH}/master_jobs_featured.csv")

print(df.columns.tolist())

['job_title', 'company_name', 'location', 'skills', 'experience', 'salary', 'description', 'posted_date', 'job_url', 'source', 'employment_type', 'experience_level', 'skill_count', 'ai_adoption_score', 'ai_flag', 'city_tier', 'posting_month', 'posting_year', 'salary_min', 'salary_max', 'salary_midpoint', 'hiring_complexity_score']

/tmp/ipykernel_3852/233538438.py:3: DtypeWarning: Columns (6,7,10,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"{PROCESSED_PATH}/master_jobs_featured.csv")